services:
  - type: web
    name: sentinel-bank-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: EMAIL
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: web
    name: sentinel-bank-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 10000
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production
